name: chris-ui-dev

include:
  - "../third-party/chris-backend/docker/docker-compose-dev.yaml"

services:
  dev:
    image: chris-ui:dev-env
    command: "'/srv/ChRIS-ui/node_modules/.bin/vite --host'"
    ports:
      - "127.0.0.1:5173:5173"
    volumes:
      - "${PWD}:/srv/ChRIS-ui"
    networks:
      - local
    working_dir: /srv/ChRIS-ui
  nginx:
    image: docker.io/nginx:1.29.4-trixie-perl
    volumes:
      - "${PWD}/docker/nginx-etc:/etc/nginx/conf.d"
    networks:
      - local
    ports:
      - "127.0.0.1:5174:5174"
    depends_on:
      - chris-backend
      - dev
